Controllers films users
UserNikki/java-filmorate pull request #5
Opened 2023-04-11 12:24 UTC by UserNikki

2023-04-12 06:52 UTC, Fleaman777 requested changes

2023-04-12 06:52 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        }
смысла большого в этом отлове исключения и вывода стектрейса нет, т.к. без явной обработки, все будет тоже самое, 
NPE отловится (только где-нибудь чуть выше), выведется стектрейс

поэтому этот блок можно убрать

2023-04-12 06:52 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private int generateId() {
молодец, что вынес генерацию айдишника в отдельный метод, 
так, если вдруг поменяется его логика, то это будет проще сделать в отдельном методе

2023-04-12 06:52 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public @interface ReleaseDateValidator {
что аннотация, что  FilmReleaseDateValidator
вполне себе самостоятельные классы, которые можно было бы вынести в свои файлы,

2023-04-12 06:52 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +     */
молодец, что решил разобраться, явных ошибок не заметил, выглядит все довольно четко и работоспособно

2023-04-12 06:52 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/validationtest/UserValidationTest.java
> +     */
ну тут можно сказать 2 подхода, 

1й создать обычные юнит тесты на модельные классы, что бы протестировать валидационные аннотации, 
в принципе что ты и сделал через валидатор 

2й написать интеграционные тесты на контроллеры: 
использовать MockMvc, что бы послать на контроллеры запросы с определенными параметрами/боди и проверить то, что соответственно должно  будет контроллером вернуться

подход, когда просто напрямую вызывается метод контроллера(то, как у тебя сейчас сделано), он тоже имеет место быть, и он в рабочий, 
но не совсем верный т.к. методы контроллера должны проверяться именно через mock реквесты

про MockMvc ничего нет в задании, эта тема разбирается чуть дальше, поэтому
можешь оставить как есть, т.к. все работает и проверяется, 
но если хочешь, можешь попробовать переделать через MockMvc, это не запрещается)

2023-04-14 15:40 UTC, UserNikki commented on src/test/java/ru/yandex/practicum/filmorate/validationtest/UserValidationTest.java
> +     */
почитал про MockMvc, но уже новый спринт открылся, попробую уже в следующее задание внести. Не хочу отстать от общего темпа.

2023-04-15 13:19 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/validationtest/UserValidationTest.java
> +     */
хорошо

2023-04-15 13:20 UTC, Fleaman777 approved these changes

2023-04-17 11:03 UTC, merged